[build]
  # Directory to change to before starting a build. 
  # This is where we will look for package.json/.nvmrc/etc.
  base = ''
  functions = 'functions-out'

[[redirects]]
  from = '/ptloot/:id'
  to = 'https://nfts.pooltogether.com/.netlify/functions/ptloot/[id]'
  status = 200
  force = true